RECETOX/galaxytools

- tools/xmsannotator/xmsannotator_macros.xml
I made a corresponding tag in the xmsannotator repo: https://github.com/RECETOX/xMSannotator/releases/tag/1.3.2-recetox0
> xmsannotator - pin the version of docker image we are using

- tools/retip/macros.xml
Docker image has been updated with the changes made in the [PR](https://github.com/RECETOX/Retip/pull/8).
> Use latest docker image for Retip

- tools/export_to_path/export_to_path.py
This PR reverts https://github.com/RECETOX/galaxytools/pull/32 and https://github.com/RECETOX/galaxytools/commit/271f30bf9316550dbc6b4728c8b06d7d5f3bb3eb
main reasons:
* the refactoring seems to not have been properly tested
* contains unreachable code
Additionally the subsequent PR (https://github.com/RECETOX/galaxytools/pull/38) adds undefined variables.
@maximskorik Refactoring is a fine endeavor, but should go hand in hand with proper testing of code. This particular tool is suitable to be tested locally (e.g. by changing `dir_prefix = "/mnt/sally"` to some local path for testing and serving the tool with `planemo serve`).  I've tested this a bit at https://github.com/RECETOX/galaxytools/commit/c83009184c64c4178e132f9e12170818c52f7db7 and that seems to me to be the last functioning …
> revert exporter tool refactoring

- tools/matchms/matchms_wrapper.py
> lint matchms

- tools/biotransformer/biotransformer.xml
- tools/biotransformer/test-data/output1.csv
- tools/biotransformer/test-data/output2.csv
- tools/biotransformer/test-data/output3.csv
- tools/biotransformer/wrapper_biotransformer.py
Added handling compounds without any predictions to Python wrapper as well as testing if input compound is not a mixture (Biotransformer is currently not able to deal with mixtures).
> Biotransformer: Fixed error when no predictions produced.

- tools/ramclustr/ramclustr_csv.xml
- tools/ramclustr/ramclustr_macros.xml
- tools/ramclustr/ramclustr_wrapper.R
- tools/ramclustr/ramclustr_xcms.xml
Fixed RAMClustR CSV by setting idmsms to NULL if not set, because the script tries to load the file even if it is 'None'.
fixes #76
> Fixed RAMClustR CSV by setting idmsms to NULL if not set

- tools/xmsannotator/xmsannotator_advanced.xml
Galaxy Traceback:
```
Traceback (most recent call last):
File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/__init__.py", line 1657, in handle_single_execution
flush_job=flush_job,
File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/__init__.py", line 1745, in execute
return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 311, in execute
history, inp_data, inp_dataset_collections, preserved_tags, all_permissions = self._collect_inputs(tool, trans, incoming, history, current_user_roles, collection_info)
File "/mnt/volume/shared/galaxy/server/lib/galaxy/tools/actions/__init__.py", line 263, in _collect_inputs
inp_data, all_permissions …
```
> xMSannotator - remove explicit conversion causing weird bug

- .tt_skip
- tools/export_to_path/export_to_path.py
- tools/export_to_path/export_to_path.xml
also abandon efforts to make it generic, added complexity is not worth it imo
The Thermo converter v1.3.2 does not detect outputs using the collection file discovery engine hence we do not have the information about the original filenames anymore. I took the opportunity to simplify the code and just allow the caller to specify the full path of the mzML to be created, the metadata file names are inferred from the same name.
> rewrite export tool to work with new thermo converter

- tools/matchms/matchms.xml
- tools/matchms/matchms_wrapper.py
Fixes #107 
Removed currently unused metrics and added parameters which can be used by the cosine based methods.
Tolerance determines the m/z peak selection for matching while the two power parameters influence the actual score.
> MatchMS: Added parameters to galaxy wrapper and python wrapper

- tools/matchms/matchms.xml
Increased matchMS version to 0.9.0. This is a first step to also include the ModifiedCosine metric.
Planemo tests all pass.
> Increased version to 0.9.0

- tools/matchms/formatter.py
- tools/matchms/matchms_formatter.xml
PR to support multiple tabular formats in `matchms_formatter`.
For now, `.tsv` and `.csv` formats are allowed.
This required to change both Galaxy tool wrapper to accept these formats and reading of the fils using `pandas.read_csv` function.
Close #188.
> 188 tabular formats

- tools/aplcms_to_ramclustr_converter/aplcms_to_ramclustr_converter.xml
- tools/filter_compounds/filter_compounds.xml
- tools/filter_compounds/macros.xml
- tools/matchms/matchms_filtering.xml
- tools/matchms/matchms_formatter.xml
- tools/matchms/matchms_similarity.xml
- tools/msmetaenhancer/msmetaenhancer.xml
- tools/ramclustr/ramclustr.xml
- tools/ramclustr/ramclustr_define_experiment.xml
- tools/recetox_aplcms/recetox_aplcms_hybrid.xml
- tools/recetox_aplcms/recetox_aplcms_unsupervised.xml
- tools/riassigner/riassigner.xml
- tools/waveica/waveica.xml
This is done via minor galaxy version bump. That means it will also update the repos in TTS so we will have a point in time where these repos were in sync (sort of). This could be useful in the future.
> upload all repos with green light to MTS

- tools/msmetaenhancer/msmetaenhancer.xml
- tools/msmetaenhancer/msmetaenhancer_wrapper.py
Set `matchms` logging level to `ERROR` to avoid extensive messages in stdout. This required to add `matchms` as MSME wrapper dependency.
Close #255.
> MSME matchms logging level

- tools/msmetaenhancer/msmetaenhancer.xml
Set environment variables for caching for `MSMetaEnhancer` to remove `Fontconfig error` and Matplotlib warning.
Close #312.
> MSMetaEnhancer: get rid of Fontconfig error

- .tt_skip
- tools/biotransformer/biotransformer.xml
- tools/biotransformer/macros.xml
- tools/biotransformer/test-data/output1.tsv
- tools/biotransformer/test-data/output2.tsv
- tools/biotransformer/test-data/output3.tsv
- tools/biotransformer/wrapper_biotransformer.py
Bumping biotransformer to version `3.0_20230403` indeed fixes the issue #225 on a global level (does not need to be configured in a particular Galaxy instance).
Close #359.
> Bump biotransformer to version 3.0_20230403

- tools/riassigner/riassigner.xml
Added xref to RIAssigner entry on [bio.tools](https://bio.tools/riassigner). Galaxy should pull the EDAM operations implicitly from there.
Close https://github.com/RECETOX/galaxytools/issues/373.
> RIAssigner: Add EDAM identifiers

- tools/recetox_aplcms/macros.xml
- tools/recetox_aplcms/recetox_aplcms_compute_clusters.xml
- tools/recetox_aplcms/recetox_aplcms_generate_feature_table.xml
- tools/recetox_aplcms/recetox_aplcms_merge_known_table.xml
- tools/recetox_aplcms/utils.R
Bump `recetox-aplcms` to version `0.12.0`.
This also covers the issue with the wrong ordering of sample names after the new clustering step #386. 
@hechth can you confirm this is what we wanted?
Also improved some minor issues with the parameters of some of the wrappers #387.
Close #389.
> recetox-aplcms: update to 0.12.0

- tools/recetox_xmsannotator/.shed.yml
- tools/riassigner/.shed.yml
Hi @hechth , we have installed most of the tools on Galaxy Australia but these two failed their tests because test data was missing from the cloned repos on galaxy.
> Include test-data in .shed.yml for riassigner and recetox_xmsannotator

- tools/recetox_msfinder/macros.xml
- tools/recetox_msfinder/recetox_msfinder.xml
- tools/retip/macros.xml
- tools/retip/retip_apply.xml
- tools/retip/retip_descriptors.xml
- tools/retip/retip_filter_rt.xml
- tools/retip/retip_train.xml
Added xref to retip and recetox-msfinder. Galaxy should pull the EDAM operations implicitly from there.
closes #417 closes #418
> Add EDAM identifiers: Retip and recetox-msfinder

- tools/matchms/matchms_networking.xml
Otherwise, the data can not be used in downstream tools/visualizations (or the user needs to set the datatype).
> fix matchms outputs to existing types

- tools/recetox_msfinder/macros.xml
- tools/recetox_msfinder/recetox_msfinder.xml
- tools/recetox_msfinder/test-data/log_smiles.smi
- tools/recetox_msfinder/test-data/test2_out.msp
This PR include the following:
- Updated the recetox_msfinder version to v3.5.2-rcx2
- Updated the tool parameter as per #479 
- updated command tag to include detect_errors="exit_code"
- Updated the log_smile.smi file to include smiles as the first line (now it can be used directly in the matchms subsetting tool)
- updated test data
closes #479
> Updated recetox_msfinder to v3.5.2-rcx2

- tools/qcxms/qcxms_getres.xml
- tools/qcxms/qcxms_neutral_run.xml
Typos are corrected.
closes https://github.com/RECETOX/galaxytools/issues/535
> Fixed typos

- tools/ramclustr/macros.xml
- tools/ramclustr/ramclustr.xml
- tools/ramclustr/ramclustr_wrapper.R
This PR includes the following:
- Updated RAMClustR to allow tsv for rectetox-aplcms inputs
- bump galaxy version
> Updated RAMClustR to allow tsv for rectetox-aplcms inputs

- tools/ramclustr/macros.xml
- tools/ramclustr/ramclustr.xml
- tools/ramclustr/ramclustr_wrapper.R
fixed sample name reading by disabling `check.names` for tabular inputs
closes #540
> RAMClustR: fixed sample name reading for tabular inputs

- tools/qcxms/macros.xml
- tools/qcxms/qcxms_getres.xml
- tools/qcxms/qcxms_neutral_run.xml
- tools/qcxms/qcxms_prod_run.xml
- tools/xtb/macros.xml
- tools/xtb/xtb_molecular_optimization.xml
Updated operation number for qcxms tools to "opeation_3860" (Analysis -> Spectral analysis -> Spectrum calculation)
For xtb tool, added topic_332 and operation_0297.
closes https://github.com/RECETOX/galaxytools/issues/559
> EDAM annotations for QCxMS and xTB tools

- tools/qcxms/qcxms_neutral_run.xml
- tools/qcxms/test-data/TMP.1_qcxms_in.txt
This PR introduces the advanced parameters `tstep` and `etemp` to the QCxMS neutral run. It also removes the sentence about CID, which is not implemented in this version, from the `tmax` parameter's help description. 
closes https://github.com/RECETOX/galaxytools/issues/585
> Add tstep and etemp parameters to the QCxMS tool

- tools/mfassignr/macros.xml
- tools/mfassignr/mfassignr_isofiltr.xml
- tools/mfassignr/mfassignr_snplot.xml
Signal-to-ratio parameter is now separated into `kmdn` * `SN_ratio` similarly as it's done in other functions (e.g. MFAssign). 
closes #588
> signal-to-noise separated into ratio and noise in IsoFiltR

- tools/mfassignr/macros.xml
- tools/mfassignr/mfassignr_mfassign.xml
- tools/mfassignr/mfassignr_mfassignCHO.xml
In this PR, more all available parameters based on https://github.com/skschum/MFAssignR/blob/master/MFAssignR/R/MFAssignCHO.R were added to the MFAssignCHO galaxy wrapper.
closes https://github.com/RECETOX/galaxytools/issues/590
> More parameters added to MFAssignR: MFAssignCHO and MFAssign function

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- tools/qcxms/qcxms_getres.xml
- tools/qcxms/qcxms_neutral_run.xml
- tools/qcxms/qcxms_prod_run.xml
Moved etemp parameter higher up so it for some reason doesn't overwrite the tinit parameter.
Fixes #646
> Fixed issue in QCxMS

- tools/waveica/macros.xml
- tools/waveica/waveica.xml
- tools/waveica/waveica_wrapper.R
This fixes #579 which is that waveica doesn't accept tabular files as input.
I also updated the profile to 23 keep the tool up to date.
> wavica: accept tabular as input
