- tools/biotransformer/biotransformer.xml
- tools/biotransformer/wrapper_biotransformer.py
add missing requirement
drop extra whitespace
> update biotransformer versioning to iuc standard

- tools/aplcms/.shed.yml
- tools/aplcms/aplcms_hybrid.xml
- tools/aplcms/aplcms_macros.xml
- tools/aplcms/aplcms_unsupervised.xml
To be mergeable this needs
* at least one test
* wrapper adjustments since we agreed to drop custom `feather` datatype (is this correct @xtracko @ondrejme ?)
> [WIP] add apLCMS 

- tools/xmsannotator/xmsannotator_advanced.xml
Error in stderr is actually correct behavior.
> Change xmsannotator error detection policy

- tools/retip/retip_apply.xml
- tools/retip/retip_descriptors.xml
- tools/retip/retip_train.xml
This PR will also help to test newly pushed docker image (Docker hub) for C stack error during CI process.
> Change test results comparison condition.

- tools/xmsannotator/xmsannotator_advanced.xml
- tools/xmsannotator/xmsannotator_macros.xml
- tools/xmsannotator/xmsannotator_simple.xml
> xmsannotator-1.3.2+galaxy0

- tools/export_to_path/export_to_path.py
Refactored the script. Removed unnecessary global variables.
> Exporter script

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/slash.yaml
all credit goes to the original authors:
https://github.com/galaxyproject/tools-iuc/tree/master/.github/workflows
> update IUC CI implementation

- tools/export_to_path/export_to_path.xml
- Added input for metadata from Thermo RAW converter. 
- Adjusted the *for* loop to iterate through both *mzml* and *json* inputs.
> Exporter tool input adjustment

- tools/export_to_path/export_to_path.xml
eventually maybe this could be one param accepting multiple inputs
ping @maximskorik
> exporter tool: accept any format of data, make json optional

- tools/export_to_path/export_to_path.py
which our cifs does not support
> use copyfile() instead to avoid chmod

- tools/aplcms/aplcms_hybrid.xml
- tools/aplcms/aplcms_macros.xml
- tools/aplcms/aplcms_unsupervised.xml
- favor number of assigned cores
> Aplcms 6.6.6 galaxy2

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
- .github/workflows/slash.yaml
- .tt_skip
this check would prevent CI from pushing to TTS
> CI: update check for repo owner

- tools/ramclustr/ramclustr_csv.xml
- tools/ramclustr/ramclustr_macros.xml
- tools/ramclustr/ramclustr_wrapper.R
- tools/ramclustr/ramclustr_xcms.xml
Part of #35 
Implemented the interface between RAMClustR and Galaxy in the R wrapper script for the XCMS based tool and CSV tool.
> Moved interface between RAMClustR and Galaxy into wrapper file

- tools/matchms/.shed.yml
- tools/ramclustr/.shed.yml
Added basic toolshed files for matchMS and RAMClustR
> Added toolshed files

- tools/pubchem/pubchem_fetch.xml
- tools/pubchem/pubchem_sparql.py
- tools/pubchem/pubchem_sparql.xml
Collection of tool which enables mining data from PubChemRDF sources.
> PubChemRDF Suite

- tools/hdf_converter/.shed.yml
- tools/hdf_converter/hdf_converter.xml
@martenson, could you take a look please. Does one have to specify conda collection when setting up dependencies (e.g. "conda-forge") in xml, or it is fine the way it is?
followup to https://github.com/RECETOX/galaxytools/pull/67
> HDF to csv converter. Change tool dependencies to be resolved by conda

- tools/hdf_converter/hdf_converter.py
- tools/hdf_converter/hdf_converter.xml
- Changed output label
- Fixed incorrect syntax in HELP section
> Minor changes to hdf_converter

- .github/workflows/pr.yaml
carbon copy of https://github.com/galaxyproject/tools-iuc/pull/3538/commits/48967ed5754281e8d1f4d3c87466633799789da2
> cache R deps based on matrix of R version and OS version

- tools/aplcms/aplcms_macros.xml
> update help for aplcms param

- tools/recetox_aplcms/.shed.yml
- tools/recetox_aplcms/recetox_aplcms_hybrid.xml
- tools/recetox_aplcms/recetox_aplcms_macros.xml
- tools/recetox_aplcms/recetox_aplcms_unsupervised.xml
and should not be neccessary (https://docs.galaxyproject.org/en/master/dev/schema.html#id9)
+ add main.R missing from repos
> aplcms: drop the R path requirement that breaks the env

- tools/waveica/.shed.yml
> waveica: remove typo from shed.yml

- tools/recetox_xmsannotator/macros.xml
- tools/recetox_xmsannotator/recetox_xmsannotator_advanced.xml
- tools/recetox_xmsannotator/recetox_xmsannotator_simple.xml
in https://github.com/RECETOX/galaxytools/pull/139/files I've accidentally added it to the old version 🤦‍♂️
> add creator tag to the proper files

- tools/recetox_aplcms/recetox_aplcms_hybrid.xml
- tools/recetox_aplcms/recetox_aplcms_macros.xml
- tools/recetox_aplcms/recetox_aplcms_unsupervised.xml
> aplcms: adjust naming, add creator

- tools/riassigner/macros.xml
- tools/riassigner/riassigner.xml
+ introduce sections
+ add tool profile
+ enable cubicspline method
> update riassigner to 0.3.0

- tools/waveica/waveica.xml
* replace Docker dependency with Bioconda **recetox-waveica** package
> waveica: change dependencies to Conda

- tools/ramclustr/ramclustr.xml
Separated `ramclustr` command generation from its call to a `configfile`.
Close #151.
> 151 separate ramclustr command call and generation

- tools/riassigner/macros.xml
> Bumped version to 0.3.1

- tools/riassigner/macros.xml
> Bump RIAssigner to 0.3.2

- tools/waveica/.shed.yml
> waveica: remove obsolete file from shed.yml

- tools/msmetaenhancer/macros.xml
Update `MSMetaEnhancer` to version `v0.2.1`.
> Update MSME version to v0.2.1

- tools/msmetaenhancer/macros.xml
Update MSMetaEnhancer to `v0.2.3`.
Close #266.
> Update MSME to v0.2.3

- tools/ramclustr/.shed.yml
- tools/ramclustr/ramclustr.xml
- tools/ramclustr/ramclustr_define_experiment.xml
- tools/ramclustr/ramclustr_wrapper.R
Added `RAMClustR` - define experiment wrapper to `shed.yaml`.
Close #270.
> RAMClustR: Add define experiment wrapper to shed

- README.md
Update Zenodo badge to point to the most recent version of galaxytools.
> galaxytools: update Zenodo badge in README.md

- tools/msmetaenhancer/macros.xml
Bump MSME to `v0.2.5`.
Close #305.
> Update MSMetaEnhancer to v0.2.5

- tools/msmetaenhancer/msmetaenhancer.xml
> Update MSME `v0.2.5` version `galaxy1`

- tools/recetox_msfinder/macros.xml
- tools/recetox_msfinder/recetox_msfinder.xml
This PR includes the following:
- updated tool version
- updated docker image version
- removed/commented element check parameter
Closes #323
> Msfinder version update

- tools/riassigner/macros.xml
> RIAssigner 0.3.4

- .tt_skip
- tools/rmassbank/rmassbank.r
- tools/rmassbank/rmassbank.xml
Polished RMassBank, prepared to be pushed to the main [toolshed](https://toolshed.g2.bx.psu.edu/).
> Polish RMassBank

- tools/recetox_aplcms/macros.xml
- tools/recetox_aplcms/recetox_aplcms_align_features.xml
- tools/recetox_aplcms/recetox_aplcms_compute_clusters.xml
- tools/recetox_aplcms/recetox_aplcms_compute_template.xml
- tools/recetox_aplcms/recetox_aplcms_correct_time.xml
- tools/recetox_aplcms/recetox_aplcms_generate_feature_table.xml
- tools/recetox_aplcms/recetox_aplcms_merge_known_table.xml
- tools/recetox_aplcms/recetox_aplcms_recover_weaker_signals.xml
- tools/recetox_aplcms/recetox_aplcms_remove_noise.xml
> Add EDAM identifiers to recetox-aplcms suite

- tools/ramclustr/macros.xml
- tools/ramclustr/ramclustr.xml
- tools/ramclustr/ramclustr_define_experiment.xml
> Add EDAM identifiers to ramclustr

- tools/matchms/macros.xml
- tools/matchms/matchms_networking.xml
Updated matchms version to 0.24.0
closes #440
> Updated matchms version to 0.24.0

- tools/matchms/matchms_metadata_merge.xml
- tools/matchms/matchms_subsetting.xml
updated python command to python3 in matchms merge and subsetting galaxy tool
> updated python in matchms merge and subsetting tool

- tools/misc/macros.xml
- tools/misc/use_theoretical_mz_annotations.xml
> fix use_theoretical_mz_annotations tools

- tools/gc_derivatization/.shed.yml
- tools/gc_derivatization/gc_derivatization.xml
- tools/gc_derivatization/macros.xml
- tools/gc_derivatization/test-data/input.tabular
This PR implements a MeOX and TMS GC-derivatization tool that reads a list of SMILES from SMI and Tabular formats.
Closes https://github.com/RECETOX/galaxytools/issues/295
> MeOX & TMS GC-Derivatization Tool

- tools/waveica/waveica.xml
- tools/waveica/waveica_wrapper.R
This PR includes the following:
- Updated WaveICA to allow integer class column type
- bump galaxy version
closes https://github.com/RECETOX/WaveICA/issues/12
> Updated WaveICA to allow integer class column type

- tools/matchms/help.xml
> Update matchms help.xml

- tools/rem_complex/rem_complex.xml
This PR expanded the "creator" macro.
closes https://github.com/RECETOX/galaxytools/issues/510
> Expanded  creator tag

- tools/waveica/waveica.xml
- tools/waveica/waveica_wrapper.R
Added group value for the standard. 
_once we have the new release, the batchwise function call params will need an update._
> Added group value for standard

- tools/mfassignr/macros.xml
- tools/mfassignr/mfassignr_findRecalSeries.xml
Adding value to non-optional parameter.
> hotfix for findrecalseries

- tools/recetox_aplcms/recetox_aplcms_correct_time.xml
This was a mistake from my side - I forgot that the tool is parallelized over the input collection.
Reverts RECETOX/galaxytools#596
Closes #600
> Revert "Force input of rt correction in recetox-aplcms to be a collection"

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
> Update planemo CI pipeline

- tools/spec2vec/spec2vec_similarity.xml
Closes #684 and closes #681
Updated the spec2vec wrapper to remove the inplace=True statement and also added a description to the similarity wrapper
> Updated spec2vec similarity tool

- tools/mztabm/.shed.yml
- tools/mztabm/mztabm_validate.xml
- tools/mztabm/test-data/MTBLS263.mztab
> mztab-m validation tool

- tools/bioconductor-scp/bioconductor_scp.xml
- tools/bioconductor-scp/macros.xml
> fix linting for bioconductor-scp tool
